# -*- mode: ruby -*-
# vi: set ft=ruby :

LB_IP_ADDRESS = "192.168.205.30"
PRIMARY_MASTER_ADDRESS = "192.168.205.11"

lb = [
    {
        :name => "loadbalancer",
        :box => "ubuntu/xenial64",
        :box_version => "20180831.0.0",
        :eth1 => "#{LB_IP_ADDRESS}",
        :mem => "512",
        :cpu => "1"
    }
]

servers = [
    {
        :name => "master-1",
        :type => "primarymaster",
        :box => "ubuntu/xenial64",
        :box_version => "20180831.0.0",
        :eth1 => "#{PRIMARY_MASTER_ADDRESS}",
        :mem => "2048",
        :cpu => "2"
    },
    {
        :name => "master-2",
        :type => "additionalmaster",
        :box => "ubuntu/xenial64",
        :box_version => "20180831.0.0",
        :eth1 => "192.168.205.12",
        :mem => "2048",
        :cpu => "2"
    },
    {
        :name => "worker-1",
        :type => "node",
        :box => "ubuntu/xenial64",
        :box_version => "20180831.0.0",
        :eth1 => "192.168.205.21",
        :mem => "1024",
        :cpu => "1"
    },
    {
        :name => "worker-2",
        :type => "node",
        :box => "ubuntu/xenial64",
        :box_version => "20180831.0.0",
        :eth1 => "192.168.205.22",
        :mem => "1024",
        :cpu => "1"
    }
]

# This script is to setup HAProxy to point to the master nodes
$configureLB = <<-SCRIPT
    apt-get update
    apt install haproxy -y
    cat <<EOFF | sudo tee /etc/haproxy/haproxy.cfg 
frontend kubernetes
    bind #{LB_IP_ADDRESS}:6443
    option tcplog
    mode tcp
    default_backend kubernetes-master-nodes

backend kubernetes-master-nodes
    mode tcp
    balance roundrobin
    option tcp-check
    server master-1 #{PRIMARY_MASTER_ADDRESS}:6443 check fall 3 rise 2
    server master-2 192.168.205.12:6443 check fall 3 rise 2
EOFF
    systemctl restart haproxy
    systemctl enable haproxy
SCRIPT

# This script to install k8s using kubeadm will get executed after a box is provisioned
$configureBox = <<-SCRIPT
    # Install Docker
    apt-get update
    apt-get install -y apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    add-apt-repository "deb https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable"
    apt-get update && apt-get install -y docker-ce=$(apt-cache madison docker-ce | grep 19.03 | head -1 | awk '{print $3}')
    usermod -aG docker vagrant

    # install kubeadm
    apt-get install -y apt-transport-https curl
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
    cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
    deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
    apt-get update
    apt-get install -y kubelet=1.18.0-00 kubeadm=1.18.0-00 kubectl=1.18.0-00
    apt-mark hold kubelet kubeadm kubectl

    # kubelet requires swap off
    swapoff -a
    # keep swap off after reboot
    sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    # ip of this box
    IP_ADDR=`ifconfig enp0s8 | grep Mask | awk '{print $2}'| cut -f2 -d:`

    # set node-ip
    touch /etc/default/kubelet
    echo KUBELET_EXTRA_ARGS=--node-ip=$IP_ADDR >> /etc/default/kubelet
    sudo systemctl restart kubelet
SCRIPT

$configurePrimaryMaster = <<-SCRIPT
    echo "This is primary master"

    # ip of this box
    IP_ADDR=`ifconfig enp0s8 | grep Mask | awk '{print $2}'| cut -f2 -d:`

    # generate cert key
    CERTKEY=$(kubeadm alpha certs certificate-key)

    # install k8s master
    HOST_NAME=$(hostname -s)
    kubeadm init --apiserver-advertise-address=$IP_ADDR --control-plane-endpoint #{LB_IP_ADDRESS}:6443 --node-name $HOST_NAME --pod-network-cidr=172.16.0.0/16 --upload-certs --certificate-key $CERTKEY --kubernetes-version 1.18.0

    #copying credentials to regular user - vagrant
    sudo --user=vagrant mkdir -p /home/vagrant/.kube
    cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    chown $(id -u vagrant):$(id -g vagrant) /home/vagrant/.kube/config
    echo alias k=kubectl >> /home/vagrant/.bashrc

    # Install Weave network addon -- commented out. Please install your own choice of network add-on.
    #kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\\n')"

    # Generate node join command script
    kubeadm token create --print-join-command >> /etc/kubeadm_join_cmd.sh
    chmod +x /etc/kubeadm_join_cmd.sh

    # Generate control plane join command script
    echo $(kubeadm token create --print-join-command) --apiserver-advertise-address=\\$1 --control-plane --certificate-key $CERTKEY > /etc/kubeadm_controlplane_cmd.sh
    chmod +x /etc/kubeadm_controlplane_cmd.sh

    # required for setting up password less ssh between guest VMs
    sudo sed -i "/^[^#]*PasswordAuthentication[[:space:]]no/c\PasswordAuthentication yes" /etc/ssh/sshd_config
    sudo service sshd restart
SCRIPT

$configureAdditionalMaster = <<-SCRIPT
    echo "This is additional master"

    # ip of this box
    IP_ADDR=`ifconfig enp0s8 | grep Mask | awk '{print $2}'| cut -f2 -d:`

    # install k8s master
    HOST_NAME=$(hostname -s)

    apt-get install -y sshpass
    sshpass -p "vagrant" scp -o StrictHostKeyChecking=no vagrant@#{PRIMARY_MASTER_ADDRESS}:/etc/kubeadm_controlplane_cmd.sh .
    sh ./kubeadm_controlplane_cmd.sh ${IP_ADDR}
SCRIPT

$configureNode = <<-SCRIPT
    echo "This is worker"
    apt-get install -y sshpass
    sshpass -p "vagrant" scp -o StrictHostKeyChecking=no vagrant@#{PRIMARY_MASTER_ADDRESS}:/etc/kubeadm_join_cmd.sh .
    sh ./kubeadm_join_cmd.sh
SCRIPT

Vagrant.configure("2") do |config|

    lb.each do |opts|
        config.vm.define opts[:name] do |config|
            config.vm.box = opts[:box]
            config.vm.box_version = opts[:box_version]
            config.vm.hostname = opts[:name]
            config.vm.network :private_network, ip: opts[:eth1]

            config.vm.provider "virtualbox" do |v|

                v.name = opts[:name]
                v.customize ["modifyvm", :id, "--memory", opts[:mem]]
                v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]

            end

            config.vm.provision "shell", inline: $configureLB
        end
    end

    servers.each do |opts|
        config.vm.define opts[:name] do |config|

            config.vm.box = opts[:box]
            config.vm.box_version = opts[:box_version]
            config.vm.hostname = opts[:name]
            config.vm.network :private_network, ip: opts[:eth1]

            config.vm.provider "virtualbox" do |v|

                v.name = opts[:name]
                v.customize ["modifyvm", :id, "--memory", opts[:mem]]
                v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]

            end

            config.vm.provision "shell", inline: $configureBox

            if opts[:type] == "primarymaster"
                config.vm.provision "shell", inline: $configurePrimaryMaster
            elsif opts[:type] == "additionalmaster"
                config.vm.provision "shell", inline: $configureAdditionalMaster
            else
                config.vm.provision "shell", inline: $configureNode
            end

        end

    end

end 

#    # install Calico pod network addon
#    export KUBECONFIG=/etc/kubernetes/admin.conf
#    kubectl apply -f https://raw.githubusercontent.com/ecomm-integration-ballerina/kubernetes-cluster/master/calico/rbac-kdd.yaml
#    kubectl apply -f https://raw.githubusercontent.com/ecomm-integration-ballerina/kubernetes-cluster/master/calico/calico.yaml